# .streamlit/secrets.toml

[connections.competition]
dialect = "mysql"
host = "localhost"
url="mysqldb://Rjchauhan:Rjchauhan@18@192.168.0.134:3306/competition"
port = 3306
database = "competition"
username = "root"
password = "Rjchauhan@18"